/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author José Luis López
 */
public class Cambiar_Contrasena extends javax.swing.JFrame {

    /**
     * Creates new form Cambiar_Contrasena
     */
    public Cambiar_Contrasena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Cambiar_Contrasena = new javax.swing.JButton();
        Contrasena = new javax.swing.JTextField();
        Confirmar_Contrasena = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Fondo_Cambiar_Contrasena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Iniciar sesión ");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 150, 40));

        Cambiar_Contrasena.setBackground(new java.awt.Color(50, 130, 250));
        Cambiar_Contrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cambiar_Contrasena.setForeground(new java.awt.Color(255, 255, 255));
        Cambiar_Contrasena.setText("Continuar");
        getContentPane().add(Cambiar_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 150, 40));

        Contrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Contrasena.setText("Nueva contraseña");
        Contrasena.setToolTipText("");
        Contrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 210, 45));

        Confirmar_Contrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Confirmar_Contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Confirmar_Contrasena.setText("Confirmar contraseña");
        Confirmar_Contrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(Confirmar_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 210, 45));

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Cambiar contraseña");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        Fondo_Cambiar_Contrasena.setBackground(new java.awt.Color(0, 0, 0));
        Fondo_Cambiar_Contrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/Cambiar_Contraseña_Al.jpg"))); // NOI18N
        getContentPane().add(Fondo_Cambiar_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambiar_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambiar_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambiar_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLCambiar_Contrasenambiar_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambiar_Contrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Cambiar_Contrasena;
    public javax.swing.JTextField Confirmar_Contrasena;
    public javax.swing.JTextField Contrasena;
    private javax.swing.JLabel Fondo_Cambiar_Contrasena;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
