/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author José Luis López
 */
public class Cambiar_Contrasena_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Cambiar_Contrasena_Usuario
     */
    public Cambiar_Contrasena_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Correo_Usuario = new javax.swing.JTextField();
        Codigo = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        Continuar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Obtener_Codigo = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Correo_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Correo_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Correo_Usuario.setText("Correo electronico / Usuario");
        Correo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Correo_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Correo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 260, 35));

        Codigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Codigo.setText("Código de verificación");
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 160, 35));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Restablecer tu contraseña");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        Continuar.setBackground(new java.awt.Color(50, 130, 250));
        Continuar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Continuar.setText("Continuar");
        getContentPane().add(Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 120, 30));

        Regresar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Regresar.setText("Iniciar sesión");
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 120, 30));

        Obtener_Codigo.setBackground(new java.awt.Color(204, 204, 204));
        Obtener_Codigo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Obtener_Codigo.setText("Obtener");
        getContentPane().add(Obtener_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 90, 35));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/Cambiar_Contraseña.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Correo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Correo_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Correo_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambiar_Contrasena_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambiar_Contrasena_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambiar_Contrasena_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambiar_Contrasena_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambiar_Contrasena_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Codigo;
    public javax.swing.JButton Continuar;
    public javax.swing.JTextField Correo_Usuario;
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton Obtener_Codigo;
    public javax.swing.JButton Regresar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
