/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//com.mycompany.proyecto_marvel_bd.Proyecto_Marvel_BD
package Vista;

/**
 *
 * @author José Luis López
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Iniciar_sesion = new javax.swing.JButton();
        CrearCuenta = new javax.swing.JButton();
        Olvido_Contrasena = new javax.swing.JButton();
        Usuario_Login = new javax.swing.JTextField();
        Contrasena_Login = new javax.swing.JTextField();
        LogoAvanger = new javax.swing.JLabel();
        Marvel = new javax.swing.JLabel();
        Borde_Menu = new javax.swing.JLabel();
        Fondologin = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iniciar_sesion.setBackground(new java.awt.Color(50, 130, 250));
        Iniciar_sesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Iniciar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        Iniciar_sesion.setText("Iniciar sesión");
        getContentPane().add(Iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 230, 45));

        CrearCuenta.setBackground(new java.awt.Color(46, 199, 62));
        CrearCuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        CrearCuenta.setText("Crear cuenta nueva");
        CrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 230, 45));

        Olvido_Contrasena.setBackground(new java.awt.Color(0, 0, 0));
        Olvido_Contrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Olvido_Contrasena.setForeground(new java.awt.Color(255, 255, 255));
        Olvido_Contrasena.setText("¿Olvidaste tu contraseña?");
        Olvido_Contrasena.setBorder(null);
        getContentPane().add(Olvido_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 240, 45));

        Usuario_Login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario_Login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Usuario_Login.setText("Usuario");
        Usuario_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 230, 45));

        Contrasena_Login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Contrasena_Login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Contrasena_Login.setText("Contraseña");
        Contrasena_Login.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(Contrasena_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 230, 45));

        LogoAvanger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/LogoA.jpg"))); // NOI18N
        getContentPane().add(LogoAvanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 310, 210));

        Marvel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/marvel.png"))); // NOI18N
        getContentPane().add(Marvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 280, 80));

        Borde_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/Cuadrado_Bo.jpg"))); // NOI18N
        Borde_Menu.setText("jLabel2");
        getContentPane().add(Borde_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 350, 520));

        Fondologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/guardianes_fondo.jpg"))); // NOI18N
        getContentPane().add(Fondologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Usuario_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuario_LoginActionPerformed

    private void CrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Borde_Menu;
    public javax.swing.JTextField Contrasena_Login;
    public javax.swing.JButton CrearCuenta;
    public javax.swing.JLabel Fondologin;
    public javax.swing.JButton Iniciar_sesion;
    private javax.swing.JLabel LogoAvanger;
    private javax.swing.JLabel Marvel;
    public javax.swing.JButton Olvido_Contrasena;
    public javax.swing.JTextField Usuario_Login;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
